name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # You can use either ubuntu-latest or pin a specific version
    # runs-on: ubuntu-latest
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Required to specify the distribution
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew build
